analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1038444368168712
  brandStrength: 1
  lightness: 0.9744884818792343
  brandColors:
    - '#00000A'
    - '#50310E'
    - '#115479'
    - '#B5A48C'
    - '#F1F5DB'
  rhythmicContrast: 0.4322576858103275
typography_spectrum: 0.7939068
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5670426
favicon: null
name: 1217bishop
